# Generated by Django 2.2.7 on 2020-05-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tournaments',
        ),
    ]
