version: '3.7'

services:
    web:
        build: .
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:80 
        environment:
            - ENVIRONMENT=production
            - SECRET_KEY=c8tng6*b=h2xe^f1eor33+2v*!hnnt75wd@xgs48@ft=^4b)th
            - DEBUG=0
            - EMAIL_HOST_USER=apikey
            - EMAIL_HOST_PASSWORD=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
        volumes:
            - .:/code
            - static_volume:/code/staticfiles
        networks:
            - nginx_network
            - db_network
        depends_on:
            - db
    nginx:
        image: nginx:1.17.0
        ports: 
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static_volume:/code/staticfiles
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on: 
            - web
        networks:
            - nginx_network
        # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s
        # reload; done & nginx -g \"daemon off;\"'"
    db:
        image: postgres:11
        env_file:
            - config/db/db_env
        networks:
            - db_network
        volumes:
            - db_volume:/var/lib/postgresql/data/
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew;
        # sleep 12h & wait $${!}; done;'"
networks:
    nginx_network:
        driver: bridge
    db_network:
        driver: bridge
volumes:
    db_volume:
    static_volume: