# Generated by Django 2.2.7 on 2020-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('link', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
