# Generated by Django 2.2.7 on 2020-05-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_name',
            new_name='name',
        ),
    ]
