# Generated by Django 2.2.7 on 2020-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200505_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='t_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
