# Generated by Django 2.2.7 on 2020-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='t_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
