# Generated by Django 2.2.7 on 2020-05-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='enddate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cost',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
