# Generated by Django 2.2.7 on 2020-05-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20200507_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
