# Generated by Django 2.2.7 on 2020-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20200507_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_payment_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
